version: "3.2"
services:
  php-fpm:
    build:
      context: './docker/php/'
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - './:/var/www/app:rw'
      - '~/.cache/composer:/var/www/.composer:rw'
    container_name: ${CONTAINER_NAME}_php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      XDEBUG_CONFIG: "remote_host=172.18.0.1 remote_enable=1"
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
    working_dir: /var/www/app
  apache:
    build:
      context: './docker/apache/'
    links:
      - php-fpm
    depends_on:
      - php-fpm
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - './:/var/www/app:rw'
      - './docker/apache/logs/:/var/log/apache2'
    container_name: ${CONTAINER_NAME}_apache
